version: "3"
services:

  flask:
    environment:
      - PUSH_GATEWAY_SERVER=pushgateway
      - BLACKBOX_SERVER=blackbox
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
#     - CA_PEM_FILE=${CA_PEM_FILE}   # this is set to a file containing  ad hoc ca anchors, the root directory of the repo so that is copied into the container   
    build: 
      context: .
      dockerfile: flask-dockerfile/Dockerfile
    ports:
      - 5000:5000

  prometheus:
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    build: 
      context: prometheus
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/alerts/:/etc/prometheus/rules.d/


  blackbox:
    image: prom/blackbox-exporter
    command: --config.file=/config/blackbox2.yml --log.level=debug
    ports:
      - 9115:9115
    volumes:
      - ./blackbox:/config

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  #redis:
  #  image: "redis:alpine"

